return function (specs, opts)
  return {
    ["@variable"]              = { fg = specs.syntax.variable },
    ["@variable.builtin"]      = { fg = specs.syntax.builtin, italic = opts.italic_comments },
    ["@variable.parameter"]    = { fg = specs.syntax.parameter },
    ["@variable.member"]       = { fg = specs.syntax.property },
    ["@constant"]              = { fg = specs.syntax.constant },
    ["@constant.builtin"]      = { fg = specs.syntax.constant, bold = opts.bold_keywords },
    ["@string"]                = { fg = specs.syntax.string },
    ["@string.regexp"]         = { fg = specs.syntax.special },
    ["@string.escape"]         = { fg = specs.syntax.special },
    ["@character"]             = { fg = specs.syntax.character },
    ["@number"]                = { fg = specs.syntax.number },
    ["@boolean"]               = { fg = specs.syntax.boolean },
    ["@number.float"]          = { fg = specs.syntax.number },
    ["@function"]              = { fg = specs.syntax.fn },
    ["@function.builtin"]      = { fg = specs.syntax.fn },
    ["@function.macro"]        = { fg = specs.syntax.macro },
    ["@method"]                = { fg = specs.syntax.fn },
    ["@constructor"]           = { fg = specs.syntax.type },
    ["@keyword"]               = { fg = specs.syntax.keyword, bold = opts.bold_keywords },
    ["@keyword.function"]      = { fg = specs.syntax.keyword, bold = opts.bold_keywords },
    ["@keyword.operator"]      = { fg = specs.syntax.operator },
    ["@keyword.return"]        = { fg = specs.syntax.keyword, bold = opts.bold_keywords },
    ["@operator"]              = { fg = specs.syntax.operator },
    ["@punctuation.delimiter"] = { fg = specs.syntax.delimiter },
    ["@punctuation.bracket"]   = { fg = specs.syntax.delimiter },
    ["@punctuation.special"]   = { fg = specs.syntax.special },
    ["@comment"]               = { fg = specs.syntax.comment, italic = opts.italic_comments },
    ["@comment.note"]          = { fg = specs.diag.info , bold = true },
    ["@comment.error"]         = { fg = specs.diag.error, bold = true },
    ["@comment.warning"]       = { fg = specs.diag.warn , bold = true },
    ["@comment.todo"]          = { fg = specs.diag.hint , bold = true },
    ["@type"]                  = { fg = specs.syntax.type },
    ["@type.builtin"]          = { fg = specs.syntax.type },
    ["@type.definition"]       = { fg = specs.syntax.type },
    ["@property"]              = { fg = specs.syntax.property },
    ["@tag"]                   = { fg = specs.syntax.tag },
    ["@tag.attribute"]         = { fg = specs.syntax.parameter },
    ["@tag.delimiter"]         = { fg = specs.syntax.delimiter },
  };
end
