# ------------------------------------------------
# Alacritty Colors
# Theme: Scotopia
# Source: https://github.com/alacritty/alacritty
# ------------------------------------------------

[colors.primary]
background = "#0F1115"
foreground = "#EFE3CD"

[colors.cursor]
text   = "#0F1115"
cursor = "#EFE3CD"

[colors.normal]
black   = "#0F1115"
red     = "#B91C1C"
green   = "#14532D"
yellow  = "#FACC15"
blue    = "#1E1B4B"
magenta = "#BE123C"
cyan    = "#0369A1"
white   = "#EFE3CD"

[colors.bright]
black   = "#0F1115"
red     = "#F76C6C"
green   = "#98C379"
yellow  = "#FACC15"
blue    = "#8EA0C2"
magenta = "#BE123C"
cyan    = "#0369A1"
white   = "#EFE3CD"
