# vim:ft=kitty

## name: ${_style_name}
## license: MIT
## author: Sayan Shankhari
## upstream: ${_upstream_url}


foreground            #E8DFD8
background            #0F1115
selection_foreground  #0F1115
selection_background  #E8DFD8
cursor                #E8DFD8
cursor_text_color     #0F1115

# Black
color0  #0F1115
color8  #0F1115

# Red
color1  #F76C6C
color9  #F76C6C

# Green
color2  #98C379
color10 #98C379

# Yellow
color3  #FACC15
color11 #FACC15

# Blue
color4  #8EA0C2
color12 #8EA0C2

# Magenta
color5  #E54888
color13 #E54888

# Cyan
color6  #38BDF8
color14 #38BDF8

# White
color7  #E8DFD8
color15 #E8DFD8
