# vim:ft=kitty

## Name: Kitty Colors
## Theme: Scotopia
## Source: https://sw.kovidgoyal.net/kitty/conf.html

foreground            #EFE3CD
background            #0F1115
selection_foreground  #0F1115
selection_background  #EFE3CD
cursor                #EFE3CD
cursor_text_color     #0F1115

# Normal & Bright Colors
color0  #0F1115
color8  #0F1115
color1  #B91C1C
color9  #F76C6C
color2  #14532D
color10 #98C379
color3  #FACC15
color11 #FACC15
color4  #1E1B4B
color12 #8EA0C2
color5  #BE123C
color13 #E54888
color6  #0369A1
color14 #38BDF8
color7  #EFE3CD
color15 #E8DFD8
