name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
#  stylua:
#    name: Code Formatting (StyLua)
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run StyLua
#        uses: JohnnyMorganz/stylua-action@v5
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          version: v2.0.2
#          args: --check .

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neovim_version: [stable, nightly]
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim (${{ matrix.neovim_version }})
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Run Plenary Tests
        run: |
          chmod +x tests/run.sh
          sh tests/run.sh
